2022-08-23 18:31:34,517 - INFO - MainThread - Logging clouni-configuration-tool started
2022-08-23 18:31:34,522 - INFO - MainThread - Server is going to start on 127.0.0.1:50052
2022-08-23 18:31:34,562 - INFO - MainThread - Server started
2022-08-23 18:31:38,182 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-23 18:31:38,183 - INFO - ThreadPoolExecutor-0_0 - Request - status OK
2022-08-23 18:31:42,293 - INFO - ThreadPoolExecutor-0_0 - Response send
2022-08-23 18:34:14,332 - INFO - MainThread - Server stopped
2022-08-23 18:34:14,332 - INFO - MainThread - Exited
2022-08-23 18:34:16,159 - INFO - MainThread - Logging clouni-configuration-tool started
2022-08-23 18:34:16,167 - INFO - MainThread - Server is going to start on 127.0.0.1:50052
2022-08-23 18:34:16,170 - INFO - MainThread - Server started
2022-08-23 18:34:20,384 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-23 18:34:20,385 - INFO - ThreadPoolExecutor-0_0 - Request - status OK
2022-08-23 18:45:14,100 - INFO - MainThread - Server stopped
2022-08-23 18:45:14,102 - INFO - MainThread - Exited
2022-08-23 18:45:17,487 - INFO - MainThread - Logging clouni-configuration-tool started
2022-08-23 18:45:17,499 - INFO - MainThread - Server is going to start on 127.0.0.1:50052
2022-08-23 18:45:17,509 - INFO - MainThread - Server started
2022-08-23 18:45:21,581 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-23 18:45:21,581 - INFO - ThreadPoolExecutor-0_0 - Request - status OK
2022-08-23 18:45:25,656 - INFO - MainThread - Server stopped
2022-08-23 18:45:25,658 - INFO - MainThread - Exited
2022-08-23 18:45:29,154 - INFO - MainThread - Logging clouni-configuration-tool started
2022-08-23 18:45:29,165 - INFO - MainThread - Server is going to start on 127.0.0.1:50052
2022-08-23 18:45:29,181 - INFO - MainThread - Server started
2022-08-23 18:45:30,401 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-23 18:45:30,401 - INFO - ThreadPoolExecutor-0_0 - Request - status OK
2022-08-23 19:12:12,977 - INFO - MainThread - Server stopped
2022-08-23 19:12:12,980 - INFO - MainThread - Exited
2022-08-23 19:12:31,651 - INFO - MainThread - Logging clouni-configuration-tool started
2022-08-23 19:12:31,656 - INFO - MainThread - Server is going to start on 127.0.0.1:50052
2022-08-23 19:12:31,657 - INFO - MainThread - Server started
2022-08-23 19:22:03,925 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-23 19:22:03,925 - INFO - ThreadPoolExecutor-0_0 - Request - status OK
2022-08-23 19:22:08,040 - INFO - ThreadPoolExecutor-0_0 - Response send
2022-08-23 19:22:15,475 - INFO - MainThread - Server stopped
2022-08-23 19:22:15,475 - INFO - MainThread - Exited
2022-08-23 19:22:30,860 - INFO - MainThread - Logging clouni-configuration-tool started
2022-08-23 19:22:30,869 - INFO - MainThread - Server is going to start on 127.0.0.1:50052
2022-08-23 19:22:30,871 - INFO - MainThread - Server started
2022-08-23 19:22:32,856 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-23 19:22:32,856 - INFO - ThreadPoolExecutor-0_0 - Request - status OK
2022-08-23 19:32:10,430 - INFO - MainThread - Server stopped
2022-08-23 19:32:10,431 - INFO - MainThread - Exited
2022-08-23 19:32:13,006 - INFO - MainThread - Logging clouni-configuration-tool started
2022-08-23 19:32:13,024 - INFO - MainThread - Server is going to start on 127.0.0.1:50052
2022-08-23 19:32:13,048 - INFO - MainThread - Server started
2022-08-23 19:32:15,813 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-23 19:32:15,814 - INFO - ThreadPoolExecutor-0_0 - Request - status OK
2022-08-23 19:32:19,930 - INFO - ThreadPoolExecutor-0_0 - Response send
2022-08-23 19:33:30,107 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-23 19:33:30,107 - INFO - ThreadPoolExecutor-0_0 - Request - status OK
2022-08-23 19:33:34,221 - INFO - ThreadPoolExecutor-0_0 - Response send
2022-08-23 19:34:51,722 - INFO - MainThread - Server stopped
2022-08-23 19:34:51,722 - INFO - MainThread - Exited
2022-08-23 19:34:53,425 - INFO - MainThread - Logging clouni-configuration-tool started
2022-08-23 19:34:53,434 - INFO - MainThread - Server is going to start on 127.0.0.1:50052
2022-08-23 19:34:53,436 - INFO - MainThread - Server started
2022-08-23 19:34:56,530 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-23 19:34:56,530 - INFO - ThreadPoolExecutor-0_0 - Request - status OK
2022-08-23 19:37:25,957 - INFO - MainThread - Server stopped
2022-08-23 19:37:25,957 - INFO - MainThread - Exited
2022-08-23 19:37:28,469 - INFO - MainThread - Logging clouni-configuration-tool started
2022-08-23 19:37:28,478 - INFO - MainThread - Server is going to start on 127.0.0.1:50052
2022-08-23 19:37:28,480 - INFO - MainThread - Server started
2022-08-23 19:37:31,146 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-23 19:37:31,146 - INFO - ThreadPoolExecutor-0_0 - Request - status OK
2022-08-23 19:37:40,843 - INFO - MainThread - Server stopped
2022-08-23 19:37:40,844 - INFO - MainThread - Exited
2022-08-23 19:37:43,502 - INFO - MainThread - Logging clouni-configuration-tool started
2022-08-23 19:37:43,506 - INFO - MainThread - Server is going to start on 127.0.0.1:50052
2022-08-23 19:37:43,508 - INFO - MainThread - Server started
2022-08-23 19:37:50,974 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-23 19:37:50,975 - INFO - ThreadPoolExecutor-0_0 - Request - status OK
2022-08-23 19:37:55,087 - INFO - ThreadPoolExecutor-0_0 - Response send
2022-08-23 19:38:01,466 - INFO - MainThread - Server stopped
2022-08-23 19:38:01,466 - INFO - MainThread - Exited
2022-08-23 19:38:31,096 - INFO - MainThread - Logging clouni-configuration-tool started
2022-08-23 19:38:31,104 - INFO - MainThread - Server is going to start on 127.0.0.1:50052
2022-08-23 19:38:31,107 - INFO - MainThread - Server started
2022-08-23 19:38:35,269 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-23 19:38:35,269 - INFO - ThreadPoolExecutor-0_0 - Request - status OK
2022-08-23 19:38:56,172 - INFO - MainThread - Server stopped
2022-08-23 19:38:56,173 - INFO - MainThread - Exited
2022-08-23 19:43:43,087 - INFO - MainThread - Logging clouni-configuration-tool started
2022-08-23 19:43:43,095 - INFO - MainThread - Server is going to start on 127.0.0.1:50052
2022-08-23 19:43:43,099 - INFO - MainThread - Server started
2022-08-23 19:43:46,011 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-23 19:43:46,011 - INFO - ThreadPoolExecutor-0_0 - Request - status OK
2022-08-23 19:43:50,127 - INFO - ThreadPoolExecutor-0_0 - Response send
2022-08-23 19:49:44,650 - INFO - MainThread - Server stopped
2022-08-23 19:49:44,650 - INFO - MainThread - Exited
2022-08-23 19:49:51,812 - INFO - MainThread - Logging clouni-configuration-tool started
2022-08-23 19:49:51,820 - INFO - MainThread - Server is going to start on 127.0.0.1:50052
2022-08-23 19:49:51,823 - INFO - MainThread - Server started
2022-08-23 19:49:55,688 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-23 19:49:55,688 - INFO - ThreadPoolExecutor-0_0 - Request - status OK
2022-08-23 19:49:55,710 - ERROR - ThreadPoolExecutor-0_0 - 
Traceback (most recent call last):
  File "/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py", line 64, in ClouniConfigurationTool
    response.content = TranslatorServer(args).output
  File "/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py", line 48, in __init__
    log_level=self.log_level, debug=self.debug)
  File "/home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/common/translator_to_configuration_dsl.py", line 46, in translate
    for key in provider_template.get('node_templates').keys():
AttributeError: 'NoneType' object has no attribute 'keys'
2022-08-23 19:49:55,710 - INFO - ThreadPoolExecutor-0_0 - Request - status ERROR
2022-08-23 19:49:55,710 - INFO - ThreadPoolExecutor-0_0 - Response send
2022-08-23 19:51:13,618 - INFO - MainThread - Server stopped
2022-08-23 19:51:13,618 - INFO - MainThread - Exited
2022-08-23 19:51:15,211 - INFO - MainThread - Logging clouni-configuration-tool started
2022-08-23 19:51:15,216 - INFO - MainThread - Server is going to start on 127.0.0.1:50052
2022-08-23 19:51:15,218 - INFO - MainThread - Server started
2022-08-23 19:51:20,645 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-23 19:51:20,645 - INFO - ThreadPoolExecutor-0_0 - Request - status OK
2022-08-23 19:51:20,666 - ERROR - ThreadPoolExecutor-0_0 - 
Traceback (most recent call last):
  File "/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py", line 64, in ClouniConfigurationTool
    response.content = TranslatorServer(args).output
  File "/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py", line 48, in __init__
    log_level=self.log_level, debug=self.debug)
  File "/home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/common/translator_to_configuration_dsl.py", line 46, in translate
    for key in provider_template.get('node_templates').keys():
AttributeError: 'NoneType' object has no attribute 'keys'
2022-08-23 19:51:20,667 - INFO - ThreadPoolExecutor-0_0 - Request - status ERROR
2022-08-23 19:51:20,667 - INFO - ThreadPoolExecutor-0_0 - Response send
2022-08-23 19:52:01,602 - INFO - MainThread - Server stopped
2022-08-23 19:52:01,602 - INFO - MainThread - Exited
2022-08-23 19:52:03,142 - INFO - MainThread - Logging clouni-configuration-tool started
2022-08-23 19:52:03,146 - INFO - MainThread - Server is going to start on 127.0.0.1:50052
2022-08-23 19:52:03,148 - INFO - MainThread - Server started
2022-08-23 19:52:07,471 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-23 19:52:07,471 - INFO - ThreadPoolExecutor-0_0 - Request - status OK
2022-08-23 19:52:11,586 - INFO - ThreadPoolExecutor-0_0 - Response send
2022-08-23 19:52:29,306 - INFO - MainThread - Server stopped
2022-08-23 19:52:29,307 - INFO - MainThread - Exited
2022-08-24 13:14:03,613 - INFO - MainThread - Logging clouni-configuration-tool started
2022-08-24 13:14:03,624 - INFO - MainThread - Server is going to start on 127.0.0.1:50052
2022-08-24 13:14:03,625 - INFO - MainThread - Server started
2022-08-24 13:14:28,620 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-24 13:14:28,621 - INFO - ThreadPoolExecutor-0_0 - Request - status OK
2022-08-24 13:14:32,734 - INFO - ThreadPoolExecutor-0_0 - Response send
2022-08-24 13:46:43,806 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-24 13:46:43,806 - INFO - ThreadPoolExecutor-0_0 - Request - status OK
2022-08-24 13:46:47,926 - INFO - ThreadPoolExecutor-0_0 - Response send
2022-08-24 13:49:25,369 - INFO - ThreadPoolExecutor-0_1 - Request received
2022-08-24 13:49:25,369 - INFO - ThreadPoolExecutor-0_1 - Request - status OK
2022-08-24 13:49:29,484 - INFO - ThreadPoolExecutor-0_1 - Response send
2022-08-24 13:50:37,624 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-24 13:50:37,624 - INFO - ThreadPoolExecutor-0_0 - Request - status OK
2022-08-24 13:50:41,736 - INFO - ThreadPoolExecutor-0_0 - Response send
2022-08-24 13:51:35,046 - INFO - ThreadPoolExecutor-0_2 - Request received
2022-08-24 13:51:35,046 - INFO - ThreadPoolExecutor-0_2 - Request - status OK
2022-08-24 13:51:39,158 - INFO - ThreadPoolExecutor-0_2 - Response send
2022-08-24 13:59:32,781 - INFO - ThreadPoolExecutor-0_1 - Request received
2022-08-24 13:59:32,781 - INFO - ThreadPoolExecutor-0_1 - Request - status OK
2022-08-24 13:59:36,893 - INFO - ThreadPoolExecutor-0_1 - Response send
2022-08-24 14:03:36,999 - INFO - ThreadPoolExecutor-0_3 - Request received
2022-08-24 14:03:36,999 - INFO - ThreadPoolExecutor-0_3 - Request - status OK
2022-08-24 14:03:37,001 - ERROR - ThreadPoolExecutor-0_3 - 
Traceback (most recent call last):
  File "/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py", line 64, in ClouniConfigurationTool
    response.content = TranslatorServer(args).output
  File "/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py", line 48, in __init__
    log_level=self.log_level, debug=self.debug)
  File "/home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/common/translator_to_configuration_dsl.py", line 43, in translate
    provider_template = provider_template.get(TOPOLOGY_TEMPLATE)
AttributeError: 'str' object has no attribute 'get'
2022-08-24 14:03:37,001 - INFO - ThreadPoolExecutor-0_3 - Request - status ERROR
2022-08-24 14:03:37,001 - INFO - ThreadPoolExecutor-0_3 - Response send
2022-08-24 14:03:44,306 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-24 14:03:44,306 - INFO - ThreadPoolExecutor-0_0 - Request - status OK
2022-08-24 14:03:44,308 - ERROR - ThreadPoolExecutor-0_0 - 
Traceback (most recent call last):
  File "/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py", line 64, in ClouniConfigurationTool
    response.content = TranslatorServer(args).output
  File "/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py", line 48, in __init__
    log_level=self.log_level, debug=self.debug)
  File "/home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/common/translator_to_configuration_dsl.py", line 43, in translate
    provider_template = provider_template.get(TOPOLOGY_TEMPLATE)
AttributeError: 'str' object has no attribute 'get'
2022-08-24 14:03:44,308 - INFO - ThreadPoolExecutor-0_0 - Request - status ERROR
2022-08-24 14:03:44,308 - INFO - ThreadPoolExecutor-0_0 - Response send
2022-08-24 14:12:25,877 - INFO - ThreadPoolExecutor-0_4 - Request received
2022-08-24 14:12:25,878 - INFO - ThreadPoolExecutor-0_4 - Request - status OK
2022-08-24 14:12:29,991 - INFO - ThreadPoolExecutor-0_4 - Response send
2022-08-24 14:12:44,441 - INFO - ThreadPoolExecutor-0_2 - Request received
2022-08-24 14:12:44,441 - INFO - ThreadPoolExecutor-0_2 - Request - status OK
2022-08-24 14:12:48,554 - INFO - ThreadPoolExecutor-0_2 - Response send
2022-08-24 14:13:27,334 - INFO - ThreadPoolExecutor-0_5 - Request received
2022-08-24 14:13:27,334 - INFO - ThreadPoolExecutor-0_5 - Request - status OK
2022-08-24 14:13:31,454 - INFO - ThreadPoolExecutor-0_5 - Response send
2022-08-24 14:15:54,162 - INFO - ThreadPoolExecutor-0_1 - Request received
2022-08-24 14:15:54,162 - INFO - ThreadPoolExecutor-0_1 - Request - status OK
2022-08-24 14:15:55,225 - ERROR - ThreadPoolExecutor-0_1 - 
Traceback (most recent call last):
  File "/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py", line 64, in ClouniConfigurationTool
    response.content = TranslatorServer(args).output
  File "/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py", line 48, in __init__
    log_level=self.log_level, debug=self.debug)
  File "/home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/common/translator_to_configuration_dsl.py", line 63, in translate
    inputs=tosca.inputs, outputs=tosca.outputs, extra=extra, debug=debug)
  File "/home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/configuration_tools/ansible/configuration_tool.py", line 101, in to_dsl
    if v['operation'] == 'create':
TypeError: 'ProviderResource' object is not subscriptable
2022-08-24 14:15:55,226 - INFO - ThreadPoolExecutor-0_1 - Request - status ERROR
2022-08-24 14:15:55,226 - INFO - ThreadPoolExecutor-0_1 - Response send
2022-08-24 14:16:12,536 - INFO - ThreadPoolExecutor-0_6 - Request received
2022-08-24 14:16:12,536 - INFO - ThreadPoolExecutor-0_6 - Request - status OK
2022-08-24 14:16:13,600 - ERROR - ThreadPoolExecutor-0_6 - 
Traceback (most recent call last):
  File "/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py", line 64, in ClouniConfigurationTool
    response.content = TranslatorServer(args).output
  File "/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py", line 48, in __init__
    log_level=self.log_level, debug=self.debug)
  File "/home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/common/translator_to_configuration_dsl.py", line 63, in translate
    inputs=tosca.inputs, outputs=tosca.outputs, extra=extra, debug=debug)
  File "/home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/configuration_tools/ansible/configuration_tool.py", line 101, in to_dsl
    if v['operation'] == 'create':
TypeError: 'ProviderResource' object is not subscriptable
2022-08-24 14:16:13,601 - INFO - ThreadPoolExecutor-0_6 - Request - status ERROR
2022-08-24 14:16:13,601 - INFO - ThreadPoolExecutor-0_6 - Response send
2022-08-24 14:16:44,391 - INFO - ThreadPoolExecutor-0_3 - Request received
2022-08-24 14:16:44,391 - INFO - ThreadPoolExecutor-0_3 - Request - status OK
2022-08-24 14:16:45,440 - ERROR - ThreadPoolExecutor-0_3 - 
Traceback (most recent call last):
  File "/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py", line 64, in ClouniConfigurationTool
    response.content = TranslatorServer(args).output
  File "/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py", line 48, in __init__
    log_level=self.log_level, debug=self.debug)
  File "/home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/common/translator_to_configuration_dsl.py", line 63, in translate
    inputs=tosca.inputs, outputs=tosca.outputs, extra=extra, debug=debug)
  File "/home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/configuration_tools/ansible/configuration_tool.py", line 101, in to_dsl
    if v['operation'] == 'create':
TypeError: 'ProviderResource' object is not subscriptable
2022-08-24 14:16:45,441 - INFO - ThreadPoolExecutor-0_3 - Request - status ERROR
2022-08-24 14:16:45,441 - INFO - ThreadPoolExecutor-0_3 - Response send
2022-08-24 14:16:48,544 - INFO - ThreadPoolExecutor-0_7 - Request received
2022-08-24 14:16:48,544 - INFO - ThreadPoolExecutor-0_7 - Request - status OK
2022-08-24 14:16:51,622 - INFO - ThreadPoolExecutor-0_7 - Response send
2022-08-24 14:17:35,765 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-24 14:17:35,765 - INFO - ThreadPoolExecutor-0_0 - Request - status OK
2022-08-24 14:17:38,849 - INFO - ThreadPoolExecutor-0_0 - Response send
2022-08-24 14:21:17,949 - INFO - ThreadPoolExecutor-0_8 - Request received
2022-08-24 14:21:17,950 - INFO - ThreadPoolExecutor-0_8 - Request - status OK
2022-08-24 14:21:19,000 - ERROR - ThreadPoolExecutor-0_8 - 
Traceback (most recent call last):
  File "/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py", line 64, in ClouniConfigurationTool
    response.content = TranslatorServer(args).output
  File "/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py", line 48, in __init__
    log_level=self.log_level, debug=self.debug)
  File "/home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/common/translator_to_configuration_dsl.py", line 63, in translate
    inputs=tosca.inputs, outputs=tosca.outputs, extra=extra, debug=debug)
  File "/home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/configuration_tools/ansible/configuration_tool.py", line 101, in to_dsl
    if v['operation'] == 'create':
TypeError: 'ProviderResource' object is not subscriptable
2022-08-24 14:21:19,000 - INFO - ThreadPoolExecutor-0_8 - Request - status ERROR
2022-08-24 14:21:19,000 - INFO - ThreadPoolExecutor-0_8 - Response send
2022-08-24 14:22:06,437 - INFO - ThreadPoolExecutor-0_4 - Request received
2022-08-24 14:22:06,437 - INFO - ThreadPoolExecutor-0_4 - Request - status OK
2022-08-24 14:22:07,497 - ERROR - ThreadPoolExecutor-0_4 - 
Traceback (most recent call last):
  File "/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py", line 64, in ClouniConfigurationTool
    response.content = TranslatorServer(args).output
  File "/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py", line 48, in __init__
    log_level=self.log_level, debug=self.debug)
  File "/home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/common/translator_to_configuration_dsl.py", line 63, in translate
    inputs=tosca.inputs, outputs=tosca.outputs, extra=extra, debug=debug)
  File "/home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/configuration_tools/ansible/configuration_tool.py", line 101, in to_dsl
    if v['operation'] == 'create':
TypeError: 'ProviderResource' object is not subscriptable
2022-08-24 14:22:07,497 - INFO - ThreadPoolExecutor-0_4 - Request - status ERROR
2022-08-24 14:22:07,497 - INFO - ThreadPoolExecutor-0_4 - Response send
2022-08-24 14:23:21,961 - INFO - MainThread - Server stopped
2022-08-24 14:23:21,961 - INFO - MainThread - Exited
2022-08-24 14:23:24,104 - INFO - MainThread - Logging clouni-configuration-tool started
2022-08-24 14:23:24,113 - INFO - MainThread - Server is going to start on 127.0.0.1:50052
2022-08-24 14:23:24,115 - INFO - MainThread - Server started
2022-08-24 14:23:27,709 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-24 14:23:27,710 - INFO - ThreadPoolExecutor-0_0 - Request - status OK
2022-08-24 14:24:47,894 - INFO - MainThread - Server stopped
2022-08-24 14:24:47,895 - INFO - MainThread - Exited
2022-08-24 14:24:51,229 - INFO - MainThread - Logging clouni-configuration-tool started
2022-08-24 14:24:51,238 - INFO - MainThread - Server is going to start on 127.0.0.1:50052
2022-08-24 14:24:51,242 - INFO - MainThread - Server started
2022-08-24 14:24:53,278 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-24 14:24:53,278 - INFO - ThreadPoolExecutor-0_0 - Request - status OK
2022-08-24 14:25:00,455 - ERROR - ThreadPoolExecutor-0_0 - 
Traceback (most recent call last):
  File "/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py", line 64, in ClouniConfigurationTool
    response.content = TranslatorServer(args).output
  File "/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py", line 48, in __init__
    log_level=self.log_level, debug=self.debug)
  File "/home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/common/translator_to_configuration_dsl.py", line 63, in translate
    inputs=tosca.inputs, outputs=tosca.outputs, extra=extra, debug=debug)
  File "/home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/configuration_tools/ansible/configuration_tool.py", line 101, in to_dsl
    if v['operation'] == 'create':
TypeError: 'ProviderResource' object is not subscriptable
2022-08-24 14:25:00,457 - INFO - ThreadPoolExecutor-0_0 - Request - status ERROR
2022-08-24 14:25:00,457 - INFO - ThreadPoolExecutor-0_0 - Response send
2022-08-24 14:27:34,450 - INFO - MainThread - Server stopped
2022-08-24 14:27:34,452 - INFO - MainThread - Exited
2022-08-24 14:27:35,934 - INFO - MainThread - Logging clouni-configuration-tool started
2022-08-24 14:27:35,939 - INFO - MainThread - Server is going to start on 127.0.0.1:50052
2022-08-24 14:27:35,940 - INFO - MainThread - Server started
2022-08-24 14:27:38,699 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-24 14:27:38,699 - INFO - ThreadPoolExecutor-0_0 - Request - status OK
2022-08-24 14:27:41,767 - INFO - ThreadPoolExecutor-0_0 - Response send
2022-08-24 14:33:23,440 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-24 14:33:23,440 - INFO - ThreadPoolExecutor-0_0 - Request - status OK
2022-08-24 14:33:26,505 - INFO - ThreadPoolExecutor-0_0 - Response send
2022-08-24 14:54:51,236 - INFO - ThreadPoolExecutor-0_1 - Request received
2022-08-24 14:54:51,236 - INFO - ThreadPoolExecutor-0_1 - Request - status OK
2022-08-24 14:54:54,322 - INFO - ThreadPoolExecutor-0_1 - Response send
2022-08-24 14:58:55,244 - INFO - MainThread - Server stopped
2022-08-24 14:58:55,245 - INFO - MainThread - Exited
2022-08-24 14:58:56,783 - INFO - MainThread - Logging clouni-configuration-tool started
2022-08-24 14:58:56,788 - INFO - MainThread - Server is going to start on 127.0.0.1:50052
2022-08-24 14:58:56,789 - INFO - MainThread - Server started
2022-08-24 14:58:59,836 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-24 14:58:59,836 - INFO - ThreadPoolExecutor-0_0 - Request - status OK
2022-08-24 15:00:22,132 - INFO - MainThread - Server stopped
2022-08-24 15:00:22,132 - INFO - MainThread - Exited
2022-08-24 15:00:23,833 - INFO - MainThread - Logging clouni-configuration-tool started
2022-08-24 15:00:23,840 - INFO - MainThread - Server is going to start on 127.0.0.1:50052
2022-08-24 15:00:23,842 - INFO - MainThread - Server started
2022-08-24 15:00:27,543 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-24 15:00:27,543 - INFO - ThreadPoolExecutor-0_0 - Request - status OK
2022-08-24 15:00:27,599 - ERROR - ThreadPoolExecutor-0_0 - 
Traceback (most recent call last):
  File "/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py", line 64, in ClouniConfigurationTool
    response.content = TranslatorServer(args).output
  File "/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py", line 48, in __init__
    log_level=self.log_level, debug=self.debug)
  File "/home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/common/translator_to_configuration_dsl.py", line 57, in translate
    tool = get_configuration_tool_class(configuration_tool)(provider)
  File "/home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/configuration_tools/ansible/configuration_tool.py", line 47, in __init__
    raise Exception("Configuration parameter \'%s\' is missing in Ansible configuration" % param)
Exception: Configuration parameter 'initial_artifacts_directory' is missing in Ansible configuration
2022-08-24 15:00:27,600 - INFO - ThreadPoolExecutor-0_0 - Request - status ERROR
2022-08-24 15:00:27,600 - INFO - ThreadPoolExecutor-0_0 - Response send
2022-08-24 15:00:33,232 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-24 15:00:33,232 - INFO - ThreadPoolExecutor-0_0 - Request - status OK
2022-08-24 15:00:33,288 - ERROR - ThreadPoolExecutor-0_0 - 
Traceback (most recent call last):
  File "/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py", line 64, in ClouniConfigurationTool
    response.content = TranslatorServer(args).output
  File "/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py", line 48, in __init__
    log_level=self.log_level, debug=self.debug)
  File "/home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/common/translator_to_configuration_dsl.py", line 57, in translate
    tool = get_configuration_tool_class(configuration_tool)(provider)
  File "/home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/configuration_tools/ansible/configuration_tool.py", line 47, in __init__
    raise Exception("Configuration parameter \'%s\' is missing in Ansible configuration" % param)
Exception: Configuration parameter 'initial_artifacts_directory' is missing in Ansible configuration
2022-08-24 15:00:33,288 - INFO - ThreadPoolExecutor-0_0 - Request - status ERROR
2022-08-24 15:00:33,288 - INFO - ThreadPoolExecutor-0_0 - Response send
2022-08-24 15:00:44,771 - INFO - MainThread - Server stopped
2022-08-24 15:00:44,771 - INFO - MainThread - Exited
2022-08-24 15:00:46,695 - INFO - MainThread - Logging clouni-configuration-tool started
2022-08-24 15:00:46,699 - INFO - MainThread - Server is going to start on 127.0.0.1:50052
2022-08-24 15:00:46,700 - INFO - MainThread - Server started
2022-08-24 15:00:49,083 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-24 15:00:49,084 - INFO - ThreadPoolExecutor-0_0 - Request - status OK
2022-08-24 15:01:56,237 - INFO - MainThread - Server stopped
2022-08-24 15:01:56,237 - INFO - MainThread - Exited
2022-08-24 15:01:57,894 - INFO - MainThread - Logging clouni-configuration-tool started
2022-08-24 15:01:57,898 - INFO - MainThread - Server is going to start on 127.0.0.1:50052
2022-08-24 15:01:57,900 - INFO - MainThread - Server started
2022-08-24 15:02:00,915 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-24 15:02:00,915 - INFO - ThreadPoolExecutor-0_0 - Request - status OK
2022-08-24 15:02:04,636 - INFO - MainThread - Server stopped
2022-08-24 15:02:04,636 - INFO - MainThread - Exited
2022-08-24 15:02:16,669 - INFO - MainThread - Logging clouni-configuration-tool started
2022-08-24 15:02:16,674 - INFO - MainThread - Server is going to start on 127.0.0.1:50052
2022-08-24 15:02:16,676 - INFO - MainThread - Server started
2022-08-24 15:02:18,646 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-24 15:02:18,646 - INFO - ThreadPoolExecutor-0_0 - Request - status OK
2022-08-24 15:02:18,703 - ERROR - ThreadPoolExecutor-0_0 - 
Traceback (most recent call last):
  File "/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py", line 64, in ClouniConfigurationTool
    response.content = TranslatorServer(args).output
  File "/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py", line 48, in __init__
    log_level=self.log_level, debug=self.debug)
  File "/home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/common/translator_to_configuration_dsl.py", line 57, in translate
    tool = get_configuration_tool_class(configuration_tool)(provider)
  File "/home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/configuration_tools/ansible/configuration_tool.py", line 46, in __init__
    raise Exception("Configuration parameter \'%s\' is missing in Ansible configuration" % param)
Exception: Configuration parameter 'initial_artifacts_directory' is missing in Ansible configuration
2022-08-24 15:02:18,703 - INFO - ThreadPoolExecutor-0_0 - Request - status ERROR
2022-08-24 15:02:18,704 - INFO - ThreadPoolExecutor-0_0 - Response send
2022-08-24 15:45:38,977 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-24 15:45:38,977 - INFO - ThreadPoolExecutor-0_0 - Request - status OK
2022-08-24 15:45:39,031 - ERROR - ThreadPoolExecutor-0_0 - 
Traceback (most recent call last):
  File "/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py", line 64, in ClouniConfigurationTool
    response.content = TranslatorServer(args).output
  File "/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py", line 48, in __init__
    log_level=self.log_level, debug=self.debug)
  File "/home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/common/translator_to_configuration_dsl.py", line 57, in translate
    tool = get_configuration_tool_class(configuration_tool)(provider)
  File "/home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/configuration_tools/ansible/configuration_tool.py", line 46, in __init__
    raise Exception("Configuration parameter \'%s\' is missing in Ansible configuration" % param)
Exception: Configuration parameter 'initial_artifacts_directory' is missing in Ansible configuration
2022-08-24 15:45:39,031 - INFO - ThreadPoolExecutor-0_0 - Request - status ERROR
2022-08-24 15:45:39,031 - INFO - ThreadPoolExecutor-0_0 - Response send
2022-08-24 15:46:46,170 - INFO - ThreadPoolExecutor-0_1 - Request received
2022-08-24 15:46:46,171 - INFO - ThreadPoolExecutor-0_1 - Request - status OK
2022-08-24 15:46:46,235 - ERROR - ThreadPoolExecutor-0_1 - 
Traceback (most recent call last):
  File "/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py", line 64, in ClouniConfigurationTool
    response.content = TranslatorServer(args).output
  File "/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py", line 48, in __init__
    log_level=self.log_level, debug=self.debug)
  File "/home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/common/translator_to_configuration_dsl.py", line 57, in translate
    tool = get_configuration_tool_class(configuration_tool)(provider)
  File "/home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/configuration_tools/ansible/configuration_tool.py", line 46, in __init__
    raise Exception("Configuration parameter \'%s\' is missing in Ansible configuration" % param)
Exception: Configuration parameter 'initial_artifacts_directory' is missing in Ansible configuration
2022-08-24 15:46:46,236 - INFO - ThreadPoolExecutor-0_1 - Request - status ERROR
2022-08-24 15:46:46,236 - INFO - ThreadPoolExecutor-0_1 - Response send
2022-08-24 15:56:15,560 - INFO - MainThread - Server stopped
2022-08-24 15:56:15,560 - INFO - MainThread - Exited
2022-08-24 15:56:46,906 - INFO - MainThread - Logging clouni-configuration-tool started
2022-08-24 15:56:46,911 - INFO - MainThread - Server is going to start on 127.0.0.1:50052
2022-08-24 15:56:46,917 - INFO - MainThread - Server started
2022-08-24 15:56:50,277 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-24 15:56:50,277 - INFO - ThreadPoolExecutor-0_0 - Request - status OK
2022-08-24 15:56:50,335 - ERROR - ThreadPoolExecutor-0_0 - 
Traceback (most recent call last):
  File "/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py", line 64, in ClouniConfigurationTool
    response.content = TranslatorServer(args).output
  File "/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py", line 48, in __init__
    log_level=self.log_level, debug=self.debug)
  File "/home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/common/translator_to_configuration_dsl.py", line 57, in translate
    tool = get_configuration_tool_class(configuration_tool)(provider)
  File "/home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/configuration_tools/ansible/configuration_tool.py", line 46, in __init__
    raise Exception("Configuration parameter \'%s\' is missing in Ansible configuration" % param)
Exception: Configuration parameter 'initial_artifacts_directory' is missing in Ansible configuration
2022-08-24 15:56:50,336 - INFO - ThreadPoolExecutor-0_0 - Request - status ERROR
2022-08-24 15:56:50,336 - INFO - ThreadPoolExecutor-0_0 - Response send
2022-08-24 15:56:56,668 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-24 15:56:56,668 - INFO - ThreadPoolExecutor-0_0 - Request - status OK
2022-08-24 15:56:59,749 - INFO - ThreadPoolExecutor-0_0 - Response send
2022-08-24 15:58:26,303 - INFO - ThreadPoolExecutor-0_1 - Request received
2022-08-24 15:58:26,304 - INFO - ThreadPoolExecutor-0_1 - Request - status OK
2022-08-24 15:58:29,390 - INFO - ThreadPoolExecutor-0_1 - Response send
2022-08-24 16:13:39,448 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-24 16:13:39,449 - INFO - ThreadPoolExecutor-0_0 - Request - status OK
2022-08-24 16:13:42,525 - INFO - ThreadPoolExecutor-0_0 - Response send
2022-08-24 16:14:18,614 - INFO - ThreadPoolExecutor-0_2 - Request received
2022-08-24 16:14:18,614 - INFO - ThreadPoolExecutor-0_2 - Request - status OK
2022-08-24 16:14:21,695 - INFO - ThreadPoolExecutor-0_2 - Response send
2022-08-24 16:16:26,525 - INFO - ThreadPoolExecutor-0_1 - Request received
2022-08-24 16:16:26,525 - INFO - ThreadPoolExecutor-0_1 - Request - status OK
2022-08-24 16:16:26,534 - ERROR - ThreadPoolExecutor-0_1 - 
Traceback (most recent call last):
  File "/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py", line 64, in ClouniConfigurationTool
    response.content = TranslatorServer(args).output
  File "/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py", line 48, in __init__
    log_level=self.log_level, debug=self.debug)
  File "/home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/common/translator_to_configuration_dsl.py", line 55, in translate
    host_ip_parameter, is_delete)
  File "/home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/providers/common/tosca_template.py", line 25, in __init__
    self.provider_config = ProviderConfiguration(self.provider)
  File "/home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/providers/common/provider_configuration.py", line 42, in __init__
    raise Exception("Configuration files were missing in possible locations: %s" % json.dumps(filename_variants_priority))
Exception: Configuration files were missing in possible locations: ["/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/tosca.cfg", "/home/sadimer/Desktop/clouni_configuration_tool/tosca.cfg", "/home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/providers/tosca/provider.cfg", "/home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/providers/tosca/tosca.cfg"]
2022-08-24 16:16:26,534 - INFO - ThreadPoolExecutor-0_1 - Request - status ERROR
2022-08-24 16:16:26,534 - INFO - ThreadPoolExecutor-0_1 - Response send
2022-08-24 16:23:58,025 - INFO - ThreadPoolExecutor-0_3 - Request received
2022-08-24 16:23:58,025 - INFO - ThreadPoolExecutor-0_3 - Request - status OK
2022-08-24 16:24:01,101 - INFO - ThreadPoolExecutor-0_3 - Response send
2022-08-24 16:24:15,525 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-24 16:24:15,526 - INFO - ThreadPoolExecutor-0_0 - Request - status OK
2022-08-24 16:24:18,603 - INFO - ThreadPoolExecutor-0_0 - Response send
2022-08-24 17:28:39,581 - INFO - MainThread - Server stopped
2022-08-24 17:28:39,581 - INFO - MainThread - Exited
2022-08-24 17:29:06,054 - INFO - MainThread - Logging clouni-configuration-tool started
2022-08-24 17:29:06,059 - INFO - MainThread - Server is going to start on 127.0.0.1:50052
2022-08-24 17:29:06,060 - INFO - MainThread - Server started
2022-08-24 17:29:57,815 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-24 17:29:57,815 - INFO - ThreadPoolExecutor-0_0 - Request - status OK
2022-08-24 17:30:00,905 - INFO - ThreadPoolExecutor-0_0 - Response send
2022-08-24 17:35:01,857 - INFO - MainThread - Server stopped
2022-08-24 17:35:01,857 - INFO - MainThread - Exited
2022-08-24 17:35:03,248 - INFO - MainThread - Logging clouni-configuration-tool started
2022-08-24 17:35:03,253 - INFO - MainThread - Server is going to start on 127.0.0.1:50052
2022-08-24 17:35:03,259 - INFO - MainThread - Server started
2022-08-24 17:35:07,693 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-24 17:35:07,693 - INFO - ThreadPoolExecutor-0_0 - Request - status OK
2022-08-24 17:35:10,780 - INFO - ThreadPoolExecutor-0_0 - Response send
2022-08-24 17:35:30,600 - INFO - MainThread - Server stopped
2022-08-24 17:35:30,601 - INFO - MainThread - Exited
2022-08-24 18:15:50,903 - INFO - MainThread - Logging clouni-configuration-tool started
2022-08-24 18:15:50,908 - INFO - MainThread - Server is going to start on 127.0.0.1:50052
2022-08-24 18:15:50,909 - INFO - MainThread - Server started
2022-08-24 18:15:57,699 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-24 18:15:57,699 - INFO - ThreadPoolExecutor-0_0 - Request - status OK
2022-08-24 18:15:57,716 - ERROR - ThreadPoolExecutor-0_0 - 
Traceback (most recent call last):
  File "/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py", line 78, in ClouniConfigurationTool
    response.content = TranslatorServer(args).output
  File "/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py", line 62, in __init__
    log_level=self.log_level, debug=self.debug)
  File "/home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/common/translator_to_configuration_dsl.py", line 60, in translate
    template = yaml.load(provider_template, Loader=Loader)
  File "/home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/yaml/__init__.py", line 79, in load
    loader = Loader(stream)
  File "/home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/yaml/loader.py", line 44, in __init__
    Reader.__init__(self, stream)
  File "/home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/yaml/reader.py", line 124, in determine_encoding
    self.update_raw()
  File "/home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/yaml/reader.py", line 178, in update_raw
    data = self.stream.read(size)
AttributeError: 'dict' object has no attribute 'read'
2022-08-24 18:15:57,717 - INFO - ThreadPoolExecutor-0_0 - Request - status ERROR
2022-08-24 18:15:57,717 - INFO - ThreadPoolExecutor-0_0 - Response send
2022-08-24 18:26:10,698 - INFO - MainThread - Server stopped
2022-08-24 18:26:10,698 - INFO - MainThread - Exited
2022-08-24 18:26:48,245 - INFO - MainThread - Logging clouni-configuration-tool started
2022-08-24 18:26:48,250 - INFO - MainThread - Server is going to start on 127.0.0.1:50052
2022-08-24 18:26:48,251 - INFO - MainThread - Server started
2022-08-24 18:27:56,142 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-24 18:27:56,142 - INFO - ThreadPoolExecutor-0_0 - Validate only request - status TEMPLATE_VALID
2022-08-24 18:27:56,210 - ERROR - ThreadPoolExecutor-0_0 - 
Traceback (most recent call last):
  File "/home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/common/translator_to_configuration_dsl.py", line 92, in translate
    tosca_parser_template_object = ToscaTemplate(yaml_dict_tpl=template)
  File "/home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/tosca_template.py", line 115, in __init__
    self.verify_template()
  File "/home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/tosca_template.py", line 312, in verify_template
    '\n\t'.join(ExceptionCollector.getExceptionsReport()))
toscaparser.common.exception.ValidationError: 
The pre-parsed input failed validation with the following error(s): 

	MissingRequiredFieldError: Template is missing required field "tosca_definitions_version".
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 884, in _bootstrap
			self._bootstrap_inner()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 916, in _bootstrap_inner
			self.run()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 864, in run
			self._target(*self._args, **self._kwargs)
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/concurrent/futures/thread.py, line 69, in _worker
			work_item.run()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/concurrent/futures/thread.py, line 56, in run
			result = self.fn(*self.args, **self.kwargs)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/grpc/_server.py, line 553, in _unary_response_in_pool
			argument, request_deserializer)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/grpc/_server.py, line 435, in _call_behavior
			response_or_iterator = behavior(argument, context)
		File /home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py, line 84, in ClouniConfigurationTool
			response.content = TranslatorServer(args).output
		File /home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py, line 64, in __init__
			log_level=self.log_level, debug=self.debug)
		File /home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/common/translator_to_configuration_dsl.py, line 92, in translate
			tosca_parser_template_object = ToscaTemplate(yaml_dict_tpl=template)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/tosca_template.py, line 99, in __init__
			self._validate_field()
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/tosca_template.py, line 264, in _validate_field
			required=DEFINITION_VERSION))

	ImportError: Relative file name "/home/sadimer/Desktop/clouni_configuration_tool/TOSCA_amazon_definition_1_0.yaml" cannot be used in a pre-parsed input template.
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 884, in _bootstrap
			self._bootstrap_inner()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 916, in _bootstrap_inner
			self.run()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 864, in run
			self._target(*self._args, **self._kwargs)
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/concurrent/futures/thread.py, line 69, in _worker
			work_item.run()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/concurrent/futures/thread.py, line 56, in run
			result = self.fn(*self.args, **self.kwargs)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/grpc/_server.py, line 553, in _unary_response_in_pool
			argument, request_deserializer)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/grpc/_server.py, line 435, in _call_behavior
			response_or_iterator = behavior(argument, context)
		File /home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py, line 84, in ClouniConfigurationTool
			response.content = TranslatorServer(args).output
		File /home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py, line 64, in __init__
			log_level=self.log_level, debug=self.debug)
		File /home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/common/translator_to_configuration_dsl.py, line 92, in translate
			tosca_parser_template_object = ToscaTemplate(yaml_dict_tpl=template)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/tosca_template.py, line 101, in __init__
			self.relationship_types = self._tpl_relationship_types()
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/tosca_template.py, line 157, in _tpl_relationship_types
			custom_rel, _ = self._get_custom_types(RELATIONSHIP_TYPES)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/tosca_template.py, line 212, in _get_custom_types
			ImportsLoader(imports, path, type_defs, self.tpl)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/imports.py, line 56, in __init__
			self._validate_and_load_imports()
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/imports.py, line 99, in _validate_and_load_imports
			None, import_def)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/imports.py, line 254, in _load_import_template
			ExceptionCollector.appendException(ImportError(msg))

	InvalidTypeError: Type "amazon.nodes.Group" is not a valid type.
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 884, in _bootstrap
			self._bootstrap_inner()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 916, in _bootstrap_inner
			self.run()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 864, in run
			self._target(*self._args, **self._kwargs)
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/concurrent/futures/thread.py, line 69, in _worker
			work_item.run()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/concurrent/futures/thread.py, line 56, in run
			result = self.fn(*self.args, **self.kwargs)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/grpc/_server.py, line 553, in _unary_response_in_pool
			argument, request_deserializer)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/grpc/_server.py, line 435, in _call_behavior
			response_or_iterator = behavior(argument, context)
		File /home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py, line 84, in ClouniConfigurationTool
			response.content = TranslatorServer(args).output
		File /home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py, line 64, in __init__
			log_level=self.log_level, debug=self.debug)
		File /home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/common/translator_to_configuration_dsl.py, line 92, in translate
			tosca_parser_template_object = ToscaTemplate(yaml_dict_tpl=template)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/tosca_template.py, line 103, in __init__
			self.topology_template = self._topology_template()
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/tosca_template.py, line 122, in _topology_template
			None)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/topology_template.py, line 57, in __init__
			self.nodetemplates = self._nodetemplates()
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/topology_template.py, line 92, in _nodetemplates
			self.rel_types)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/nodetemplate.py, line 43, in __init__
			custom_def)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/entity_template.py, line 53, in __init__
			if type is not None else None
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/elements/nodetype.py, line 32, in __init__
			super(NodeType, self).__init__(ntype, self.NODE_PREFIX, custom_def)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/elements/statefulentitytype.py, line 51, in __init__
			InvalidTypeError(what=entitytype))

	UnknownFieldError: "properties" of template "testing_tosca_group" contains unknown field "description". Refer to the definition to verify valid values.
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 884, in _bootstrap
			self._bootstrap_inner()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 916, in _bootstrap_inner
			self.run()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 864, in run
			self._target(*self._args, **self._kwargs)
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/concurrent/futures/thread.py, line 69, in _worker
			work_item.run()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/concurrent/futures/thread.py, line 56, in run
			result = self.fn(*self.args, **self.kwargs)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/grpc/_server.py, line 553, in _unary_response_in_pool
			argument, request_deserializer)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/grpc/_server.py, line 435, in _call_behavior
			response_or_iterator = behavior(argument, context)
		File /home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py, line 84, in ClouniConfigurationTool
			response.content = TranslatorServer(args).output
		File /home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py, line 64, in __init__
			log_level=self.log_level, debug=self.debug)
		File /home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/common/translator_to_configuration_dsl.py, line 92, in translate
			tosca_parser_template_object = ToscaTemplate(yaml_dict_tpl=template)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/tosca_template.py, line 103, in __init__
			self.topology_template = self._topology_template()
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/tosca_template.py, line 122, in _topology_template
			None)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/topology_template.py, line 57, in __init__
			self.nodetemplates = self._nodetemplates()
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/topology_template.py, line 97, in _nodetemplates
			tpl.validate(self)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/nodetemplate.py, line 190, in validate
			self._validate_properties(self.entity_tpl, self.type_definition)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/entity_template.py, line 174, in _validate_properties
			self._common_validate_properties(entitytype, properties)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/entity_template.py, line 228, in _common_validate_properties
			'properties')
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/entity_template.py, line 272, in _common_validate_field
			field=name))

	UnknownFieldError: "properties" of template "testing_tosca_group" contains unknown field "name". Refer to the definition to verify valid values.
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 884, in _bootstrap
			self._bootstrap_inner()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 916, in _bootstrap_inner
			self.run()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 864, in run
			self._target(*self._args, **self._kwargs)
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/concurrent/futures/thread.py, line 69, in _worker
			work_item.run()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/concurrent/futures/thread.py, line 56, in run
			result = self.fn(*self.args, **self.kwargs)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/grpc/_server.py, line 553, in _unary_response_in_pool
			argument, request_deserializer)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/grpc/_server.py, line 435, in _call_behavior
			response_or_iterator = behavior(argument, context)
		File /home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py, line 84, in ClouniConfigurationTool
			response.content = TranslatorServer(args).output
		File /home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py, line 64, in __init__
			log_level=self.log_level, debug=self.debug)
		File /home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/common/translator_to_configuration_dsl.py, line 92, in translate
			tosca_parser_template_object = ToscaTemplate(yaml_dict_tpl=template)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/tosca_template.py, line 103, in __init__
			self.topology_template = self._topology_template()
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/tosca_template.py, line 122, in _topology_template
			None)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/topology_template.py, line 57, in __init__
			self.nodetemplates = self._nodetemplates()
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/topology_template.py, line 97, in _nodetemplates
			tpl.validate(self)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/nodetemplate.py, line 190, in validate
			self._validate_properties(self.entity_tpl, self.type_definition)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/entity_template.py, line 174, in _validate_properties
			self._common_validate_properties(entitytype, properties)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/entity_template.py, line 228, in _common_validate_properties
			'properties')
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/entity_template.py, line 272, in _common_validate_field
			field=name))

	UnknownFieldError: "properties" of template "testing_tosca_group" contains unknown field "rules". Refer to the definition to verify valid values.
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 884, in _bootstrap
			self._bootstrap_inner()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 916, in _bootstrap_inner
			self.run()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 864, in run
			self._target(*self._args, **self._kwargs)
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/concurrent/futures/thread.py, line 69, in _worker
			work_item.run()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/concurrent/futures/thread.py, line 56, in run
			result = self.fn(*self.args, **self.kwargs)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/grpc/_server.py, line 553, in _unary_response_in_pool
			argument, request_deserializer)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/grpc/_server.py, line 435, in _call_behavior
			response_or_iterator = behavior(argument, context)
		File /home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py, line 84, in ClouniConfigurationTool
			response.content = TranslatorServer(args).output
		File /home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py, line 64, in __init__
			log_level=self.log_level, debug=self.debug)
		File /home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/common/translator_to_configuration_dsl.py, line 92, in translate
			tosca_parser_template_object = ToscaTemplate(yaml_dict_tpl=template)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/tosca_template.py, line 103, in __init__
			self.topology_template = self._topology_template()
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/tosca_template.py, line 122, in _topology_template
			None)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/topology_template.py, line 57, in __init__
			self.nodetemplates = self._nodetemplates()
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/topology_template.py, line 97, in _nodetemplates
			tpl.validate(self)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/nodetemplate.py, line 190, in validate
			self._validate_properties(self.entity_tpl, self.type_definition)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/entity_template.py, line 174, in _validate_properties
			self._common_validate_properties(entitytype, properties)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/entity_template.py, line 228, in _common_validate_properties
			'properties')
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/entity_template.py, line 272, in _common_validate_field
			field=name))

	UnknownFieldError: "properties" of template "testing_tosca_group" contains unknown field "rules_egress". Refer to the definition to verify valid values.
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 884, in _bootstrap
			self._bootstrap_inner()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 916, in _bootstrap_inner
			self.run()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 864, in run
			self._target(*self._args, **self._kwargs)
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/concurrent/futures/thread.py, line 69, in _worker
			work_item.run()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/concurrent/futures/thread.py, line 56, in run
			result = self.fn(*self.args, **self.kwargs)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/grpc/_server.py, line 553, in _unary_response_in_pool
			argument, request_deserializer)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/grpc/_server.py, line 435, in _call_behavior
			response_or_iterator = behavior(argument, context)
		File /home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py, line 84, in ClouniConfigurationTool
			response.content = TranslatorServer(args).output
		File /home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py, line 64, in __init__
			log_level=self.log_level, debug=self.debug)
		File /home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/common/translator_to_configuration_dsl.py, line 92, in translate
			tosca_parser_template_object = ToscaTemplate(yaml_dict_tpl=template)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/tosca_template.py, line 103, in __init__
			self.topology_template = self._topology_template()
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/tosca_template.py, line 122, in _topology_template
			None)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/topology_template.py, line 57, in __init__
			self.nodetemplates = self._nodetemplates()
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/topology_template.py, line 97, in _nodetemplates
			tpl.validate(self)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/nodetemplate.py, line 190, in validate
			self._validate_properties(self.entity_tpl, self.type_definition)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/entity_template.py, line 174, in _validate_properties
			self._common_validate_properties(entitytype, properties)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/entity_template.py, line 228, in _common_validate_properties
			'properties')
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/entity_template.py, line 272, in _common_validate_field
			field=name))

	InvalidTypeError: Type "amazon.nodes.Instance" is not a valid type.
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 884, in _bootstrap
			self._bootstrap_inner()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 916, in _bootstrap_inner
			self.run()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 864, in run
			self._target(*self._args, **self._kwargs)
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/concurrent/futures/thread.py, line 69, in _worker
			work_item.run()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/concurrent/futures/thread.py, line 56, in run
			result = self.fn(*self.args, **self.kwargs)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/grpc/_server.py, line 553, in _unary_response_in_pool
			argument, request_deserializer)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/grpc/_server.py, line 435, in _call_behavior
			response_or_iterator = behavior(argument, context)
		File /home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py, line 84, in ClouniConfigurationTool
			response.content = TranslatorServer(args).output
		File /home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py, line 64, in __init__
			log_level=self.log_level, debug=self.debug)
		File /home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/common/translator_to_configuration_dsl.py, line 92, in translate
			tosca_parser_template_object = ToscaTemplate(yaml_dict_tpl=template)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/tosca_template.py, line 103, in __init__
			self.topology_template = self._topology_template()
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/tosca_template.py, line 122, in _topology_template
			None)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/topology_template.py, line 57, in __init__
			self.nodetemplates = self._nodetemplates()
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/topology_template.py, line 92, in _nodetemplates
			self.rel_types)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/nodetemplate.py, line 43, in __init__
			custom_def)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/entity_template.py, line 53, in __init__
			if type is not None else None
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/elements/nodetype.py, line 32, in __init__
			super(NodeType, self).__init__(ntype, self.NODE_PREFIX, custom_def)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/elements/statefulentitytype.py, line 51, in __init__
			InvalidTypeError(what=entitytype))

	UnknownFieldError: "properties" of template "testing_tosca_instance" contains unknown field "name". Refer to the definition to verify valid values.
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 884, in _bootstrap
			self._bootstrap_inner()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 916, in _bootstrap_inner
			self.run()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 864, in run
			self._target(*self._args, **self._kwargs)
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/concurrent/futures/thread.py, line 69, in _worker
			work_item.run()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/concurrent/futures/thread.py, line 56, in run
			result = self.fn(*self.args, **self.kwargs)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/grpc/_server.py, line 553, in _unary_response_in_pool
			argument, request_deserializer)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/grpc/_server.py, line 435, in _call_behavior
			response_or_iterator = behavior(argument, context)
		File /home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py, line 84, in ClouniConfigurationTool
			response.content = TranslatorServer(args).output
		File /home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py, line 64, in __init__
			log_level=self.log_level, debug=self.debug)
		File /home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/common/translator_to_configuration_dsl.py, line 92, in translate
			tosca_parser_template_object = ToscaTemplate(yaml_dict_tpl=template)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/tosca_template.py, line 103, in __init__
			self.topology_template = self._topology_template()
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/tosca_template.py, line 122, in _topology_template
			None)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/topology_template.py, line 57, in __init__
			self.nodetemplates = self._nodetemplates()
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/topology_template.py, line 97, in _nodetemplates
			tpl.validate(self)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/nodetemplate.py, line 190, in validate
			self._validate_properties(self.entity_tpl, self.type_definition)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/entity_template.py, line 174, in _validate_properties
			self._common_validate_properties(entitytype, properties)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/entity_template.py, line 228, in _common_validate_properties
			'properties')
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/entity_template.py, line 272, in _common_validate_field
			field=name))

	UnknownFieldError: "properties" of template "testing_tosca_instance" contains unknown field "network". Refer to the definition to verify valid values.
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 884, in _bootstrap
			self._bootstrap_inner()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 916, in _bootstrap_inner
			self.run()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 864, in run
			self._target(*self._args, **self._kwargs)
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/concurrent/futures/thread.py, line 69, in _worker
			work_item.run()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/concurrent/futures/thread.py, line 56, in run
			result = self.fn(*self.args, **self.kwargs)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/grpc/_server.py, line 553, in _unary_response_in_pool
			argument, request_deserializer)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/grpc/_server.py, line 435, in _call_behavior
			response_or_iterator = behavior(argument, context)
		File /home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py, line 84, in ClouniConfigurationTool
			response.content = TranslatorServer(args).output
		File /home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py, line 64, in __init__
			log_level=self.log_level, debug=self.debug)
		File /home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/common/translator_to_configuration_dsl.py, line 92, in translate
			tosca_parser_template_object = ToscaTemplate(yaml_dict_tpl=template)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/tosca_template.py, line 103, in __init__
			self.topology_template = self._topology_template()
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/tosca_template.py, line 122, in _topology_template
			None)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/topology_template.py, line 57, in __init__
			self.nodetemplates = self._nodetemplates()
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/topology_template.py, line 97, in _nodetemplates
			tpl.validate(self)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/nodetemplate.py, line 190, in validate
			self._validate_properties(self.entity_tpl, self.type_definition)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/entity_template.py, line 174, in _validate_properties
			self._common_validate_properties(entitytype, properties)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/entity_template.py, line 228, in _common_validate_properties
			'properties')
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/entity_template.py, line 272, in _common_validate_field
			field=name))

	UnknownFieldError: "properties" of template "testing_tosca_instance" contains unknown field "tags". Refer to the definition to verify valid values.
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 884, in _bootstrap
			self._bootstrap_inner()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 916, in _bootstrap_inner
			self.run()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 864, in run
			self._target(*self._args, **self._kwargs)
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/concurrent/futures/thread.py, line 69, in _worker
			work_item.run()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/concurrent/futures/thread.py, line 56, in run
			result = self.fn(*self.args, **self.kwargs)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/grpc/_server.py, line 553, in _unary_response_in_pool
			argument, request_deserializer)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/grpc/_server.py, line 435, in _call_behavior
			response_or_iterator = behavior(argument, context)
		File /home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py, line 84, in ClouniConfigurationTool
			response.content = TranslatorServer(args).output
		File /home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py, line 64, in __init__
			log_level=self.log_level, debug=self.debug)
		File /home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/common/translator_to_configuration_dsl.py, line 92, in translate
			tosca_parser_template_object = ToscaTemplate(yaml_dict_tpl=template)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/tosca_template.py, line 103, in __init__
			self.topology_template = self._topology_template()
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/tosca_template.py, line 122, in _topology_template
			None)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/topology_template.py, line 57, in __init__
			self.nodetemplates = self._nodetemplates()
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/topology_template.py, line 97, in _nodetemplates
			tpl.validate(self)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/nodetemplate.py, line 190, in validate
			self._validate_properties(self.entity_tpl, self.type_definition)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/entity_template.py, line 174, in _validate_properties
			self._common_validate_properties(entitytype, properties)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/entity_template.py, line 228, in _common_validate_properties
			'properties')
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/entity_template.py, line 272, in _common_validate_field
			field=name))

	InvalidTypeError: Type "amazon.nodes.Key" is not a valid type.
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 884, in _bootstrap
			self._bootstrap_inner()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 916, in _bootstrap_inner
			self.run()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 864, in run
			self._target(*self._args, **self._kwargs)
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/concurrent/futures/thread.py, line 69, in _worker
			work_item.run()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/concurrent/futures/thread.py, line 56, in run
			result = self.fn(*self.args, **self.kwargs)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/grpc/_server.py, line 553, in _unary_response_in_pool
			argument, request_deserializer)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/grpc/_server.py, line 435, in _call_behavior
			response_or_iterator = behavior(argument, context)
		File /home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py, line 84, in ClouniConfigurationTool
			response.content = TranslatorServer(args).output
		File /home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py, line 64, in __init__
			log_level=self.log_level, debug=self.debug)
		File /home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/common/translator_to_configuration_dsl.py, line 92, in translate
			tosca_parser_template_object = ToscaTemplate(yaml_dict_tpl=template)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/tosca_template.py, line 103, in __init__
			self.topology_template = self._topology_template()
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/tosca_template.py, line 122, in _topology_template
			None)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/topology_template.py, line 57, in __init__
			self.nodetemplates = self._nodetemplates()
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/topology_template.py, line 92, in _nodetemplates
			self.rel_types)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/nodetemplate.py, line 43, in __init__
			custom_def)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/entity_template.py, line 53, in __init__
			if type is not None else None
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/elements/nodetype.py, line 32, in __init__
			super(NodeType, self).__init__(ntype, self.NODE_PREFIX, custom_def)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/elements/statefulentitytype.py, line 51, in __init__
			InvalidTypeError(what=entitytype))

	UnknownFieldError: "properties" of template "testing_tosca_key" contains unknown field "key_material". Refer to the definition to verify valid values.
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 884, in _bootstrap
			self._bootstrap_inner()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 916, in _bootstrap_inner
			self.run()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 864, in run
			self._target(*self._args, **self._kwargs)
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/concurrent/futures/thread.py, line 69, in _worker
			work_item.run()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/concurrent/futures/thread.py, line 56, in run
			result = self.fn(*self.args, **self.kwargs)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/grpc/_server.py, line 553, in _unary_response_in_pool
			argument, request_deserializer)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/grpc/_server.py, line 435, in _call_behavior
			response_or_iterator = behavior(argument, context)
		File /home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py, line 84, in ClouniConfigurationTool
			response.content = TranslatorServer(args).output
		File /home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py, line 64, in __init__
			log_level=self.log_level, debug=self.debug)
		File /home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/common/translator_to_configuration_dsl.py, line 92, in translate
			tosca_parser_template_object = ToscaTemplate(yaml_dict_tpl=template)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/tosca_template.py, line 103, in __init__
			self.topology_template = self._topology_template()
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/tosca_template.py, line 122, in _topology_template
			None)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/topology_template.py, line 57, in __init__
			self.nodetemplates = self._nodetemplates()
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/topology_template.py, line 97, in _nodetemplates
			tpl.validate(self)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/nodetemplate.py, line 190, in validate
			self._validate_properties(self.entity_tpl, self.type_definition)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/entity_template.py, line 174, in _validate_properties
			self._common_validate_properties(entitytype, properties)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/entity_template.py, line 228, in _common_validate_properties
			'properties')
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/entity_template.py, line 272, in _common_validate_field
			field=name))

	UnknownFieldError: "properties" of template "testing_tosca_key" contains unknown field "name". Refer to the definition to verify valid values.
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 884, in _bootstrap
			self._bootstrap_inner()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 916, in _bootstrap_inner
			self.run()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 864, in run
			self._target(*self._args, **self._kwargs)
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/concurrent/futures/thread.py, line 69, in _worker
			work_item.run()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/concurrent/futures/thread.py, line 56, in run
			result = self.fn(*self.args, **self.kwargs)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/grpc/_server.py, line 553, in _unary_response_in_pool
			argument, request_deserializer)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/grpc/_server.py, line 435, in _call_behavior
			response_or_iterator = behavior(argument, context)
		File /home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py, line 84, in ClouniConfigurationTool
			response.content = TranslatorServer(args).output
		File /home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py, line 64, in __init__
			log_level=self.log_level, debug=self.debug)
		File /home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/common/translator_to_configuration_dsl.py, line 92, in translate
			tosca_parser_template_object = ToscaTemplate(yaml_dict_tpl=template)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/tosca_template.py, line 103, in __init__
			self.topology_template = self._topology_template()
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/tosca_template.py, line 122, in _topology_template
			None)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/topology_template.py, line 57, in __init__
			self.nodetemplates = self._nodetemplates()
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/topology_template.py, line 97, in _nodetemplates
			tpl.validate(self)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/nodetemplate.py, line 190, in validate
			self._validate_properties(self.entity_tpl, self.type_definition)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/entity_template.py, line 174, in _validate_properties
			self._common_validate_properties(entitytype, properties)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/entity_template.py, line 228, in _common_validate_properties
			'properties')
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/entity_template.py, line 272, in _common_validate_field
			field=name))

	ValidationError: parent_req is None
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 884, in _bootstrap
			self._bootstrap_inner()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 916, in _bootstrap_inner
			self.run()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 864, in run
			self._target(*self._args, **self._kwargs)
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/concurrent/futures/thread.py, line 69, in _worker
			work_item.run()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/concurrent/futures/thread.py, line 56, in run
			result = self.fn(*self.args, **self.kwargs)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/grpc/_server.py, line 553, in _unary_response_in_pool
			argument, request_deserializer)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/grpc/_server.py, line 435, in _call_behavior
			response_or_iterator = behavior(argument, context)
		File /home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py, line 84, in ClouniConfigurationTool
			response.content = TranslatorServer(args).output
		File /home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py, line 64, in __init__
			log_level=self.log_level, debug=self.debug)
		File /home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/common/translator_to_configuration_dsl.py, line 92, in translate
			tosca_parser_template_object = ToscaTemplate(yaml_dict_tpl=template)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/tosca_template.py, line 103, in __init__
			self.topology_template = self._topology_template()
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/tosca_template.py, line 122, in _topology_template
			None)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/topology_template.py, line 60, in __init__
			self.graph = ToscaGraph(self.nodetemplates)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/tpl_relationship_graph.py, line 19, in __init__
			self._create()
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/tpl_relationship_graph.py, line 40, in _create
			relation = node.relationships
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/nodetemplate.py, line 61, in relationships
			explicit = self._get_explicit_relationship(r, value)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/nodetemplate.py, line 106, in _get_explicit_relationship
			str(parent_reqs)))


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py", line 84, in ClouniConfigurationTool
    response.content = TranslatorServer(args).output
  File "/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py", line 64, in __init__
    log_level=self.log_level, debug=self.debug)
  File "/home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/common/translator_to_configuration_dsl.py", line 95, in translate
    raise Exception("Got exception from OpenStack tosca-parser")
Exception: Got exception from OpenStack tosca-parser
2022-08-24 18:27:56,211 - INFO - ThreadPoolExecutor-0_0 - Request - status ERROR
2022-08-24 18:27:56,211 - INFO - ThreadPoolExecutor-0_0 - Response send
2022-08-24 18:29:51,314 - INFO - MainThread - Server stopped
2022-08-24 18:29:51,314 - INFO - MainThread - Exited
2022-08-24 18:30:05,712 - INFO - MainThread - Logging clouni-configuration-tool started
2022-08-24 18:30:05,720 - INFO - MainThread - Server is going to start on 127.0.0.1:50052
2022-08-24 18:30:05,723 - INFO - MainThread - Server started
2022-08-24 18:30:07,742 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-24 18:30:07,743 - INFO - ThreadPoolExecutor-0_0 - Validate only request - status TEMPLATE_VALID
2022-08-24 18:36:08,042 - INFO - MainThread - Server stopped
2022-08-24 18:36:08,043 - INFO - MainThread - Exited
2022-08-24 18:36:12,073 - INFO - MainThread - Logging clouni-configuration-tool started
2022-08-24 18:36:12,078 - INFO - MainThread - Server is going to start on 127.0.0.1:50052
2022-08-24 18:36:12,079 - INFO - MainThread - Server started
2022-08-24 18:36:16,254 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-24 18:36:16,255 - INFO - ThreadPoolExecutor-0_0 - Validate only request - status TEMPLATE_VALID
2022-08-24 18:36:16,333 - ERROR - ThreadPoolExecutor-0_0 - 
Traceback (most recent call last):
  File "/home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/common/translator_to_configuration_dsl.py", line 94, in translate
    tosca_parser_template_object = ToscaTemplate(yaml_dict_tpl=template)
  File "/home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/tosca_template.py", line 115, in __init__
    self.verify_template()
  File "/home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/tosca_template.py", line 312, in verify_template
    '\n\t'.join(ExceptionCollector.getExceptionsReport()))
toscaparser.common.exception.ValidationError: 
The pre-parsed input failed validation with the following error(s): 

	MissingRequiredFieldError: Template is missing required field "tosca_definitions_version".
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 884, in _bootstrap
			self._bootstrap_inner()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 916, in _bootstrap_inner
			self.run()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 864, in run
			self._target(*self._args, **self._kwargs)
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/concurrent/futures/thread.py, line 69, in _worker
			work_item.run()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/concurrent/futures/thread.py, line 56, in run
			result = self.fn(*self.args, **self.kwargs)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/grpc/_server.py, line 553, in _unary_response_in_pool
			argument, request_deserializer)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/grpc/_server.py, line 435, in _call_behavior
			response_or_iterator = behavior(argument, context)
		File /home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py, line 84, in ClouniConfigurationTool
			response.content = TranslatorServer(args).output
		File /home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py, line 64, in __init__
			log_level=self.log_level, debug=self.debug)
		File /home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/common/translator_to_configuration_dsl.py, line 94, in translate
			tosca_parser_template_object = ToscaTemplate(yaml_dict_tpl=template)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/tosca_template.py, line 99, in __init__
			self._validate_field()
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/tosca_template.py, line 264, in _validate_field
			required=DEFINITION_VERSION))


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py", line 84, in ClouniConfigurationTool
    response.content = TranslatorServer(args).output
  File "/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py", line 64, in __init__
    log_level=self.log_level, debug=self.debug)
  File "/home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/common/translator_to_configuration_dsl.py", line 97, in translate
    raise Exception("Got exception from OpenStack tosca-parser")
Exception: Got exception from OpenStack tosca-parser
2022-08-24 18:36:16,333 - INFO - ThreadPoolExecutor-0_0 - Request - status ERROR
2022-08-24 18:36:16,333 - INFO - ThreadPoolExecutor-0_0 - Response send
2022-08-24 18:36:28,228 - INFO - MainThread - Server stopped
2022-08-24 18:36:28,229 - INFO - MainThread - Exited
2022-08-24 18:36:31,480 - INFO - MainThread - Logging clouni-configuration-tool started
2022-08-24 18:36:31,488 - INFO - MainThread - Server is going to start on 127.0.0.1:50052
2022-08-24 18:36:31,490 - INFO - MainThread - Server started
2022-08-24 18:36:33,183 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-24 18:36:33,184 - INFO - ThreadPoolExecutor-0_0 - Validate only request - status TEMPLATE_VALID
2022-08-24 18:37:12,185 - ERROR - ThreadPoolExecutor-0_0 - 
Traceback (most recent call last):
  File "/home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/common/translator_to_configuration_dsl.py", line 94, in translate
    tosca_parser_template_object = ToscaTemplate(yaml_dict_tpl=template)
  File "/home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/tosca_template.py", line 115, in __init__
    self.verify_template()
  File "/home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/tosca_template.py", line 312, in verify_template
    '\n\t'.join(ExceptionCollector.getExceptionsReport()))
toscaparser.common.exception.ValidationError: 
The pre-parsed input failed validation with the following error(s): 

	MissingRequiredFieldError: Template is missing required field "tosca_definitions_version".
		File /home/sadimer/Downloads/pycharm-2022.1.2/plugins/python/helpers/pydev/_pydev_bundle/pydev_monkey.py, line 795, in __call__
			ret = self.original_func(*self.args, **self.kwargs)
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 884, in _bootstrap
			self._bootstrap_inner()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 916, in _bootstrap_inner
			self.run()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/threading.py, line 864, in run
			self._target(*self._args, **self._kwargs)
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/concurrent/futures/thread.py, line 69, in _worker
			work_item.run()
		File /home/sadimer/.pyenv/versions/3.6.9/lib/python3.6/concurrent/futures/thread.py, line 56, in run
			result = self.fn(*self.args, **self.kwargs)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/grpc/_server.py, line 553, in _unary_response_in_pool
			argument, request_deserializer)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/grpc/_server.py, line 435, in _call_behavior
			response_or_iterator = behavior(argument, context)
		File /home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py, line 84, in ClouniConfigurationTool
			response.content = TranslatorServer(args).output
		File /home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py, line 64, in __init__
			log_level=self.log_level, debug=self.debug)
		File /home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/common/translator_to_configuration_dsl.py, line 94, in translate
			tosca_parser_template_object = ToscaTemplate(yaml_dict_tpl=template)
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/tosca_template.py, line 99, in __init__
			self._validate_field()
		File /home/sadimer/Desktop/clouni_configuration_tool/venv/lib/python3.6/site-packages/toscaparser/tosca_template.py, line 264, in _validate_field
			required=DEFINITION_VERSION))


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py", line 84, in ClouniConfigurationTool
    response.content = TranslatorServer(args).output
  File "/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py", line 64, in __init__
    log_level=self.log_level, debug=self.debug)
  File "/home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/common/translator_to_configuration_dsl.py", line 97, in translate
    raise Exception("Got exception from OpenStack tosca-parser")
Exception: Got exception from OpenStack tosca-parser
2022-08-24 18:37:12,186 - INFO - ThreadPoolExecutor-0_0 - Request - status ERROR
2022-08-24 18:37:12,186 - INFO - ThreadPoolExecutor-0_0 - Response send
2022-08-24 18:40:12,242 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-24 18:40:12,243 - INFO - ThreadPoolExecutor-0_0 - Validate only request - status TEMPLATE_VALID
2022-08-24 18:41:17,914 - INFO - MainThread - Server stopped
2022-08-24 18:41:17,915 - INFO - MainThread - Exited
2022-08-24 18:41:20,588 - INFO - MainThread - Logging clouni-configuration-tool started
2022-08-24 18:41:20,593 - INFO - MainThread - Server is going to start on 127.0.0.1:50052
2022-08-24 18:41:20,594 - INFO - MainThread - Server started
2022-08-24 18:41:25,728 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-24 18:41:25,728 - INFO - ThreadPoolExecutor-0_0 - Validate only request - status TEMPLATE_VALID
2022-08-24 18:41:25,805 - INFO - ThreadPoolExecutor-0_0 - Response send
2022-08-24 18:42:39,003 - INFO - MainThread - Server stopped
2022-08-24 18:42:39,003 - INFO - MainThread - Exited
2022-08-24 18:42:40,108 - INFO - MainThread - Logging clouni-configuration-tool started
2022-08-24 18:42:40,113 - INFO - MainThread - Server is going to start on 127.0.0.1:50052
2022-08-24 18:42:40,114 - INFO - MainThread - Server started
2022-08-24 18:42:42,868 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-24 18:42:42,868 - INFO - ThreadPoolExecutor-0_0 - Validate only request - status TEMPLATE_VALID
2022-08-24 18:42:42,945 - INFO - ThreadPoolExecutor-0_0 - Response send
2022-08-24 18:43:10,708 - INFO - MainThread - Server stopped
2022-08-24 18:43:10,709 - INFO - MainThread - Exited
2022-08-24 18:43:12,045 - INFO - MainThread - Logging clouni-configuration-tool started
2022-08-24 18:43:12,049 - INFO - MainThread - Server is going to start on 127.0.0.1:50052
2022-08-24 18:43:12,051 - INFO - MainThread - Server started
2022-08-24 18:43:13,871 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-24 18:43:13,871 - INFO - ThreadPoolExecutor-0_0 - Validate only request - status TEMPLATE_VALID
2022-08-24 18:43:13,949 - INFO - ThreadPoolExecutor-0_0 - Response send
2022-08-24 18:43:18,044 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-24 18:43:18,044 - INFO - ThreadPoolExecutor-0_0 - Validate only request - status TEMPLATE_VALID
2022-08-24 18:43:18,111 - INFO - ThreadPoolExecutor-0_0 - Response send
2022-08-24 18:43:25,887 - INFO - ThreadPoolExecutor-0_1 - Request received
2022-08-24 18:43:25,888 - INFO - ThreadPoolExecutor-0_1 - Request - status OK
2022-08-24 18:43:29,020 - INFO - ThreadPoolExecutor-0_1 - Response send
2022-08-24 18:44:01,538 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-24 18:44:01,538 - INFO - ThreadPoolExecutor-0_0 - Request - status OK
2022-08-24 18:44:04,681 - INFO - ThreadPoolExecutor-0_0 - Response send
2022-08-24 18:49:29,130 - INFO - MainThread - Server stopped
2022-08-24 18:49:29,130 - INFO - MainThread - Exited
2022-08-24 18:49:30,243 - INFO - MainThread - Logging clouni-configuration-tool started
2022-08-24 18:49:30,248 - INFO - MainThread - Server is going to start on 127.0.0.1:50052
2022-08-24 18:49:30,250 - INFO - MainThread - Server started
2022-08-24 18:51:02,718 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-24 18:51:02,719 - INFO - ThreadPoolExecutor-0_0 - Request - status OK
2022-08-24 18:51:05,867 - INFO - ThreadPoolExecutor-0_0 - Response send
2022-08-24 18:51:17,670 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-24 18:51:17,670 - INFO - ThreadPoolExecutor-0_0 - Request - status OK
2022-08-24 18:51:20,805 - INFO - ThreadPoolExecutor-0_0 - Response send
2022-08-24 18:51:28,742 - INFO - ThreadPoolExecutor-0_1 - Request received
2022-08-24 18:51:28,743 - INFO - ThreadPoolExecutor-0_1 - Validate only request - status TEMPLATE_VALID
2022-08-24 18:51:28,811 - INFO - ThreadPoolExecutor-0_1 - Response send
2022-08-24 18:51:56,037 - INFO - ThreadPoolExecutor-0_0 - Request received
2022-08-24 18:51:56,038 - INFO - ThreadPoolExecutor-0_0 - Request - status OK
2022-08-24 18:51:56,047 - ERROR - ThreadPoolExecutor-0_0 - 
Traceback (most recent call last):
  File "/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py", line 85, in ClouniConfigurationTool
    response.content = TranslatorServer(args).output
  File "/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py", line 65, in __init__
    log_level=self.log_level, debug=self.debug)
  File "/home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/common/translator_to_configuration_dsl.py", line 54, in translate
    provider_config = ProviderConfiguration(provider)
  File "/home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/providers/common/provider_configuration.py", line 42, in __init__
    raise Exception("Configuration files were missing in possible locations: %s" % json.dumps(filename_variants_priority))
Exception: Configuration files were missing in possible locations: ["/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/tosca.cfg", "/home/sadimer/Desktop/clouni_configuration_tool/tosca.cfg", "/home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/providers/tosca/provider.cfg", "/home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/providers/tosca/tosca.cfg"]
2022-08-24 18:51:56,049 - INFO - ThreadPoolExecutor-0_0 - Request - status ERROR
2022-08-24 18:51:56,049 - INFO - ThreadPoolExecutor-0_0 - Response send
2022-08-24 18:52:08,986 - INFO - ThreadPoolExecutor-0_2 - Request received
2022-08-24 18:52:08,986 - INFO - ThreadPoolExecutor-0_2 - Request - status OK
2022-08-24 18:52:08,997 - ERROR - ThreadPoolExecutor-0_2 - 
Traceback (most recent call last):
  File "/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py", line 85, in ClouniConfigurationTool
    response.content = TranslatorServer(args).output
  File "/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/clouni_configuration_tool.py", line 65, in __init__
    log_level=self.log_level, debug=self.debug)
  File "/home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/common/translator_to_configuration_dsl.py", line 54, in translate
    provider_config = ProviderConfiguration(provider)
  File "/home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/providers/common/provider_configuration.py", line 42, in __init__
    raise Exception("Configuration files were missing in possible locations: %s" % json.dumps(filename_variants_priority))
Exception: Configuration files were missing in possible locations: ["/home/sadimer/Desktop/clouni_configuration_tool/grpc_server/tosca.cfg", "/home/sadimer/Desktop/clouni_configuration_tool/tosca.cfg", "/home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/providers/tosca/provider.cfg", "/home/sadimer/Desktop/clouni_configuration_tool/configuration_tool/providers/tosca/tosca.cfg"]
2022-08-24 18:52:08,997 - INFO - ThreadPoolExecutor-0_2 - Request - status ERROR
2022-08-24 18:52:08,997 - INFO - ThreadPoolExecutor-0_2 - Response send
2022-08-24 18:52:28,558 - INFO - ThreadPoolExecutor-0_1 - Request received
2022-08-24 18:52:28,558 - INFO - ThreadPoolExecutor-0_1 - Request - status OK
2022-08-24 18:52:31,706 - INFO - ThreadPoolExecutor-0_1 - Response send
2022-08-24 18:52:39,391 - INFO - ThreadPoolExecutor-0_6 - Request received
2022-08-24 18:52:39,391 - INFO - ThreadPoolExecutor-0_6 - Request - status OK
2022-08-24 18:52:42,529 - INFO - ThreadPoolExecutor-0_6 - Response send
2022-08-24 18:53:40,916 - INFO - MainThread - Server stopped
2022-08-24 18:53:40,916 - INFO - MainThread - Exited
